---
title: "zls"
author: "baijie"
date: "2021/12/16"
output: html_document
---

```{r data handling}
f2 = read.csv("m1.csv")
library(ggplot2)
o1=f2$m1
o2=f2$m2
o3=f2$m3
o4=f2$m4
o5=f2$m5

df1 = data.frame(
  length=o1,
  index=c(1:length(o1))
)
df2 = data.frame(
  length=o2,
  index=c(1:length(o2))
)
df3 = data.frame(
  length=o3,
  index=c(1:length(o3))
)
df4 = data.frame(
  length=o4,
  index=c(1:length(o4))
)
df5 = data.frame(
  length=o5,
  index=c(1:length(o5))
)

dataset = data.frame(
  df1,df2,df3,df4,df5
)

k1=f2$k1
k2=f2$k2
k3=f2$k3
k4=f2$k4
k5=f2$k5
Df1 = data.frame(
  length=k1,
  index=c(1:length(k1))
)
Df2 = data.frame(
  length=k2,
  index=c(1:length(k2))
)
Df3 = data.frame(
  length=k3,
  index=c(1:length(k3))
)
Df4 = data.frame(
  length=k4,
  index=c(1:length(k4))
)
Df5 = data.frame(
  length=k5,
  index=c(1:length(k5))
)

Dataset = data.frame(
  Df1,Df2,Df3,Df4,Df5
)
```

```r

ggplot(df1,aes(x=index,y=length))+
  geom_point()
ggplot(df2,aes(x=index,y=length))+
  geom_point()
ggplot(df3,aes(x=index,y=length))+
  geom_point()
ggplot(df4,aes(x=index,y=length))+
  geom_point()
ggplot(df5,aes(x=index,y=length))+
  geom_point()

```
```{r}

ggplot(dataset,aes(x=index,y=length))+
  geom_point(aes(x=index,y=length),color="red",alpha=.6,pch=16,size=3)+
  geom_point(aes(x=index.1,y=length.1),color="blue",alpha=.6,pch=17,size=4)+
  geom_point(aes(x=index.2,y=length.2),color="black",alpha=.6,pch=18,size=3)+
  geom_point(aes(x=index.3,y=length.3),color="orange",alpha=.6,pch=19,size=4)+
  geom_point(aes(x=index.4,y=length.4),color="green",alpha=.6,pch=20,size=3)+
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("木本竹样本竹节~竹节长关系")+
  scale_x_continuous(breaks=seq(0, 16, 1))+
  scale_y_continuous(breaks=seq(0, 30, 5))+
  theme(plot.title = element_text(hjust = 0.5))
  
  
ggplot(Dataset,aes(x=index,y=length))+
  geom_point(aes(x=index,y=length),color="red",alpha=.6,pch=16,size=3)+
  geom_point(aes(x=index.1,y=length.1),color="blue",alpha=.6,pch=17,size=4)+
  geom_point(aes(x=index.2,y=length.2),color="black",alpha=.6,pch=18,size=3)+
  geom_point(aes(x=index.3,y=length.3),color="orange",alpha=.6,pch=19,size=4)+
  geom_point(aes(x=index.4,y=length.4),color="green",alpha=.6,pch=20,size=3)+
  labs(x="竹节数",y="长度/单位(cm)")+  
  scale_x_continuous(breaks=seq(0, 16, 1))+
  scale_y_continuous(breaks=seq(0, 30, 5))+
    ggtitle("草本竹样本竹节~竹节长关系")+
  theme(plot.title = element_text(hjust = 0.5))


```
```{r dram lm with dots}
library(Rmisc)
library(ggpubr)
p1=ggplot(df1,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+  
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("木本竹样本1")+
  theme(plot.title = element_text(hjust = 0.5))

p2=ggplot(df2,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+  
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("木本竹样本2")+
  theme(plot.title = element_text(hjust = 0.5))

p3=ggplot(df3,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+  
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("木本竹样本3")+
  theme(plot.title = element_text(hjust = 0.5))

p4=ggplot(df4,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("木本竹样本4")+
  theme(plot.title = element_text(hjust = 0.5))

p5=ggplot(df5,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+  
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("木本竹样本5")+
  theme(plot.title = element_text(hjust = 0.5))



P1=ggplot(Df1,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+  
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("草本竹样本1")+
  theme(plot.title = element_text(hjust = 0.5))


P2=ggplot(Df2,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+  
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("草本竹样本2")+
  theme(plot.title = element_text(hjust = 0.5))


P3=ggplot(Df3,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+  
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("草本竹样本3")+
  theme(plot.title = element_text(hjust = 0.5))


P4=ggplot(Df4,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+  
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("草本竹样本4")+
  theme(plot.title = element_text(hjust = 0.5))


P5=ggplot(Df5,aes(x=index,y=length))+  
  geom_point(aes(x=index,y=length),color="black",alpha=.6,pch=16,size=1)+
  geom_smooth(method="lm",se=T)+  
  labs(x="竹节数",y="长度/单位(cm)")+
  ggtitle("草本竹样本5")+
  theme(plot.title = element_text(hjust = 0.5))

ggarrange(p1,p2,p3,p4,p5,P1,P2,P3,P4,P5+rremove("x.text"),
         
         ncol=5,nrow=2)

```

···


```{r}
lm1=lm(f2$m1~f2$n)
summary(lm1)
lm2=lm(f2$m2~f2$n)
summary(lm2)
lm3=lm(f2$m3~f2$n)
summary(lm3)
lm4=lm(f2$m4~f2$n)
summary(lm4)
lm5=lm(f2$m5~f2$n)
summary(lm5)
```


```{r}
layout(matrix(c(1:6),2,3))
plot(lm1,c(1:6))
layout(matrix(c(1:6),2,3))
plot(lm2,c(1:6))
layout(matrix(c(1:6),2,3))
plot(lm3,c(1:6))
layout(matrix(c(1:6),2,3))
plot(lm4,c(1:6))
layout(matrix(c(1:6),2,3))
plot(lm5,c(1:6))
```

```{r}
lm11=lm(f2$k1~f2$n)
summary(lm11)
lm22=lm(f2$k2~f2$n)
summary(lm22)
lm33=lm(f2$k3~f2$n)
summary(lm33)
lm44=lm(f2$k4~f2$n)
summary(lm44)
lm55=lm(f2$k5~f2$n)
summary(lm55)
```

```{r}
t.test(f2$m,f2$k)
```

```{r}
t.test(f2$m,f2$kk)
```

```{r}
plot(f2$n,f2$m1,main = "木本竹",col = "palegreen4")
abline(lm1)
```





